# Generated by Django 4.2.7 on 2023-11-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('class1', models.CharField(max_length=5)),
                ('id1', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('conform', models.CharField(max_length=20)),
            ],
        ),
    ]
