# Generated by Django 4.2.7 on 2023-11-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='id1',
            new_name='username',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
