# Generated by Django 4.2.7 on 2023-11-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_id1_userregistration_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('video', models.FileField(null=True, upload_to='videos_uploaded')),
            ],
        ),
    ]


class animation(models.Model):
    heading = models.CharField(max_length=255)
    video1 = models.FileField(upload_to="video1",null=True)
    def __str__(self):
        return self.heading
