# Generated by Django 4.2.7 on 2023-11-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_animation'),
    ]

    operations = [
        migrations.CreateModel(
            name='minigames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='quize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
            ],
        ),
    ]
