# Generated by Django 4.2.7 on 2023-11-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_minigames_quize'),
    ]

    operations = [
        migrations.AddField(
            model_name='minigames',
            name='minigames',
            field=models.FileField(null=True, upload_to='minigames'),
        ),
        migrations.AddField(
            model_name='quize',
            name='quize',
            field=models.FileField(null=True, upload_to='quize_upload'),
        ),
        migrations.AlterField(
            model_name='animation',
            name='video',
            field=models.FileField(upload_to='videos/%y'),
        ),
    ]
