# Generated by Django 4.2.7 on 2023-11-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_minigames_minigames_quize_quize_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animation',
            old_name='video',
            new_name='videos',
        ),
    ]
