# Generated by Django 4.2.7 on 2023-11-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_video_animation_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animation',
            name='videos',
        ),
        migrations.AddField(
            model_name='animation',
            name='video1',
            field=models.FileField(null=True, upload_to='video1/%y'),
        ),
    ]
