# Generated by Django 4.2.7 on 2023-11-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_animation_videos_animation_video1'),
    ]

    operations = [
        migrations.CreateModel(
            name='animation1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('video1', models.FileField(null=True, upload_to='video uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='quize',
            name='quize',
        ),
        migrations.AddField(
            model_name='quize',
            name='minigames',
            field=models.FileField(null=True, upload_to='quize'),
        ),
        migrations.AlterField(
            model_name='animation',
            name='video1',
            field=models.FileField(null=True, upload_to='video1'),
        ),
    ]
