# Generated by Django 4.2.7 on 2023-11-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_animation1_heading_animation1_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation1',
            name='caption',
            field=models.CharField(max_length=200),
        ),
    ]
