# Generated by Django 4.2.7 on 2023-12-01 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_animation1_caption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='score',
        ),
    ]
