# Generated by Django 4.2.7 on 2023-12-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quize',
        ),
    ]
