# Generated by Django 4.2.7 on 2023-12-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_quize'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quize',
            new_name='quize1',
        ),
    ]
