# Generated by Django 4.2.7 on 2023-12-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_answer_category_question_delete_quize1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption2', models.CharField(max_length=200)),
                ('video12', models.FileField(null=True, upload_to='video12/%y')),
            ],
        ),
        migrations.CreateModel(
            name='Minigames1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('minigames_file', models.FileField(null=True, upload_to='minigames')),
            ],
        ),
        migrations.CreateModel(
            name='Minigames2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('minigames_file', models.FileField(null=True, upload_to='minigames2')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.DeleteModel(
            name='minigames',
        ),
        migrations.RemoveField(
            model_name='question',
            name='c_name',
        ),
        migrations.RenameField(
            model_name='userregistration',
            old_name='username',
            new_name='Username',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
