# Generated by Django 4.2.7 on 2023-12-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_animation2_minigames1_minigames2_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animation2',
            name='video12',
        ),
        migrations.AddField(
            model_name='animation2',
            name='video2',
            field=models.FileField(null=True, upload_to='video2/%y'),
        ),
    ]
