# Generated by Django 4.2.7 on 2023-12-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_quiz_question_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='mini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('video1', models.FileField(null=True, upload_to='video1/%y')),
            ],
        ),
    ]
