# Generated by Django 4.2.7 on 2024-01-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_quiz_title_alter_userregistration_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='Username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='class1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='conform',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
