# Generated by Django 4.2.7 on 2024-01-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_userregistration_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='Username',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='class1',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='conform',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
